// Global imports
import { ExpensesTable } from "@/components/tables/Order-request";
import { OrderData } from "@/utils/Types";
import React from "react";
// Local imports

const orderDataset: OrderData[] = [
  {
    id: "ORD-001",
    dateTime: "2024-01-15T10:30:00Z",
    orderType: "Dine-in",
    customerName: "John Doe",
    items: "Pizza, Pasta, Coke",
    orderStatus: "Completed",
    amount: 25.99,
    paymentStatus: "Paid",
    createdBy: "Admin",
  },
  {
    id: "ORD-002",
    dateTime: "2024-01-15T12:15:00Z",
    orderType: "Takeaway",
    customerName: "Jane Smith",
    items: "Burger, Fries",
    orderStatus: "Pending",
    amount: 15.5,
    paymentStatus: "Unpaid",
    notes: "Extra cheese on burger",
    createdBy: "Staff1",
  },
  {
    id: "ORD-003",
    dateTime: "2024-01-15T14:45:00Z",
    orderType: "Delivery",
    customerName: "Alice Brown",
    items: "Sushi Platter",
    orderStatus: "Preparing",
    amount: 32.75,
    paymentStatus: "Paid",
    notes: "Deliver before 6 PM",
    createdBy: "Admin",
  },
  {
    id: "ORD-004",
    dateTime: "2024-01-15T18:30:00Z",
    orderType: "Dine-in",
    customerName: "Michael Johnson",
    items: "Steak, Mashed Potatoes, Wine",
    orderStatus: "Completed",
    amount: 45.99,
    paymentStatus: "Paid",
    createdBy: "Staff2",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
  {
    id: "ORD-005",
    dateTime: "2024-01-15T20:00:00Z",
    orderType: "Takeaway",
    customerName: "Emily Davis",
    items: "Salad, Smoothie",
    orderStatus: "Cancelled",
    amount: 12.5,
    paymentStatus: "Refunded",
    createdBy: "Admin",
  },
];

export default function ManageSuppliers() {
  return (
    <div className="container overflow-auto pb-20">
      <ExpensesTable data={orderDataset} />
    </div>
  );
}
