export const permissionsForRole = {
  ADMIN: {
    role: "ADMIN",
    canViewOrders: true,
    canEditOrders: true,
    canManageEmployees: true,
    canAccessReports: true,
    canManageStores: true,
    canManageInventory: true,
    canManageCategories: true,
    canAssignRoles: true,
  },
  MANAGER: {
    role: "MANAGER",
    canViewOrders: true,
    canEditOrders: true,
    canManageEmployees: true,
    canAccessReports: true,
    canManageInventory: true,
    canManageCategories: true,
    canAssignRoles: false,
  },
  ACCOUNTANT: {
    role: "ACCOUNTANT",
    canViewOrders: true,
    canEditOrders: false,
    canManageEmployees: false,
    canAccessReports: true,
    canManageStores: false,
    canManageInventory: false,
    canManageCategories: false,
    canAssignRoles: false,
  },
  STAFF: {
    role: "STAFF",
    canViewOrders: true,
    canEditOrders: false,
    canManageEmployees: false,
    canAccessReports: false,
    canManageStores: false,
    canManageInventory: false,
    canManageCategories: false,
    canAssignRoles: false,
  },
  CHEF: {
    role: "CHEF",
    canViewOrders: true,
    canEditOrders: true,
    canManageEmployees: false,
    canAccessReports: false,
    canManageStores: false,
    canManageInventory: false,
    canManageCategories: false,
    canAssignRoles: false,
  },
};
