import { CategoryTypes, Table } from "@/utils/Types";

export const productData = [
  {
    id: "1",
    title: "Spicy Chicken Bowl",
    rating: 4.5,
    addOns: ["Extra Cheese", "Spicy Sauce", "Sour Cream", "Jalapenos"],
    bowls: 2,
    persons: 1,
    price: 9.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A delicious spicy chicken bowl with fresh ingredients including tender chicken, vibrant veggies, and a kick of spice to satisfy your cravings. Perfect for a quick lunch or dinner, topped with extra cheese and spicy sauce for added flavor.",

    fetchFillings: async () => [
      { id: "1", name: "Chicken", defaultSelected: true },
      { id: "2", name: "Beef", defaultSelected: false },
      { id: "3", name: "Tofu", defaultSelected: false },
      { id: "4", name: "Grilled Vegetables", defaultSelected: false },
      { id: "5", name: "Pork", defaultSelected: false },
    ],
  },
  {
    id: "2",
    title: "Veggie Delight Bowl",
    rating: 4.2,
    addOns: ["Avocado", "Lemon", "Olives", "Feta Cheese"],
    bowls: 1,
    persons: 2,
    price: 7.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A healthy veggie delight bowl packed with nutrient-rich vegetables like lettuce, tomato, and cucumbers, all tossed in a refreshing dressing. Great for a light meal, with optional avocado and olives to add a creamy texture and extra flavour.",

    fetchFillings: async () => [
      { id: "1", name: "Lettuce", defaultSelected: true },
      { id: "2", name: "Tomato", defaultSelected: false },
      { id: "3", name: "Cucumber", defaultSelected: false },
      { id: "4", name: "Carrots", defaultSelected: false },
      { id: "5", name: "Chickpeas", defaultSelected: false },
    ],
  },
  {
    id: "3",
    title: "BBQ Beef Bowl",
    rating: 4.7,
    addOns: ["BBQ Sauce", "Grilled Corn", "Coleslaw", "Pickles"],
    bowls: 3,
    persons: 2,
    price: 12.5,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A smoky BBQ beef bowl served with grilled veggies, corn, and creamy coleslaw, topped with tangy pickles for an extra layer of flavor. The BBQ sauce adds a sweet and smoky taste, making this bowl a satisfying meal for BBQ lovers.",

    fetchFillings: async () => [
      { id: "1", name: "Beef", defaultSelected: true },
      { id: "2", name: "Pork", defaultSelected: false },
      { id: "3", name: "Chicken", defaultSelected: false },
      { id: "4", name: "Brisket", defaultSelected: false },
      { id: "5", name: "Tofu", defaultSelected: false },
    ],
  },
  {
    id: "4",
    title: "Seafood Surprise Bowl",
    rating: 4.8,
    addOns: ["Lemon", "Garlic Butter", "Herbs", "Chili Flakes"],
    bowls: 2,
    persons: 1,
    price: 14.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A bowl full of fresh seafood including shrimp, salmon, and scallops, drizzled with rich garlic butter and fresh herbs. A squeeze of lemon and a sprinkle of chili flakes add the perfect balance of zest and heat, perfect for seafood lovers.",

    fetchFillings: async () => [
      { id: "1", name: "Shrimp", defaultSelected: true },
      { id: "2", name: "Salmon", defaultSelected: false },
      { id: "3", name: "Scallops", defaultSelected: false },
      { id: "4", name: "Clams", defaultSelected: false },
      { id: "5", name: "Fish Fillet", defaultSelected: false },
    ],
  },
  {
    id: "5",
    title: "Chicken Caesar Bowl",
    rating: 4.3,
    addOns: ["Bacon", "Parmesan Cheese", "Croutons", "Avocado"],
    bowls: 1,
    persons: 2,
    price: 8.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A classic Caesar salad with grilled chicken, crispy bacon, crunchy croutons, and creamy parmesan cheese. This bowl is topped with a rich Caesar dressing for a delicious, satisfying meal.",

    fetchFillings: async () => [
      { id: "1", name: "Grilled Chicken", defaultSelected: true },
      { id: "2", name: "Fried Chicken", defaultSelected: false },
      { id: "3", name: "Tofu", defaultSelected: false },
      { id: "4", name: "Grilled Shrimp", defaultSelected: false },
      { id: "5", name: "Smoked Salmon", defaultSelected: false },
    ],
  },
  {
    id: "6",
    title: "Pulled Pork Bowl",
    rating: 4.6,
    addOns: ["Coleslaw", "Pickles", "BBQ Sauce", "Cheddar Cheese"],
    bowls: 2,
    persons: 1,
    price: 11.5,
    imageUrl: "/demo.jpg",
    itemDetails:
      "Tender pulled pork served with a sweet and tangy BBQ sauce, creamy coleslaw, and crunchy pickles for an unforgettable Southern-inspired meal. Optional cheddar cheese adds a rich, savory touch to the dish.",

    fetchFillings: async () => [
      { id: "1", name: "Pulled Pork", defaultSelected: true },
      { id: "2", name: "Brisket", defaultSelected: false },
      { id: "3", name: "Chicken", defaultSelected: false },
      { id: "4", name: "Turkey", defaultSelected: false },
      { id: "5", name: "Lamb", defaultSelected: false },
    ],
  },
  {
    id: "7",
    title: "Mushroom Medley Bowl",
    rating: 4.4,
    addOns: ["Balsamic Glaze", "Goat Cheese", "Walnuts", "Thyme"],
    bowls: 3,
    persons: 2,
    price: 10.25,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A bowl of assorted mushrooms with a tangy balsamic glaze, finished with crumbled goat cheese and a sprinkle of thyme. Walnuts add a delightful crunch, making this bowl a perfect vegetarian option.",

    fetchFillings: async () => [
      { id: "1", name: "Portobello", defaultSelected: true },
      { id: "2", name: "Shiitake", defaultSelected: false },
      { id: "3", name: "Oyster", defaultSelected: false },
      { id: "4", name: "Button", defaultSelected: false },
      { id: "5", name: "Chanterelle", defaultSelected: false },
    ],
  },
  {
    id: "8",
    title: "Falafel & Hummus Bowl",
    rating: 4.7,
    addOns: ["Tahini", "Olives", "Pickled Onions", "Pine Nuts"],
    bowls: 2,
    persons: 1,
    price: 9.2,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A Mediterranean-inspired bowl with crispy falafel, creamy hummus, and a medley of toppings including olives, pickled onions, and pine nuts. It's a great combination of savory, tangy, and crunchy textures.",

    fetchFillings: async () => [
      { id: "1", name: "Falafel", defaultSelected: true },
      { id: "2", name: "Hummus", defaultSelected: false },
      { id: "3", name: "Grilled Vegetables", defaultSelected: false },
      { id: "4", name: "Tabbouleh", defaultSelected: false },
      { id: "5", name: "Couscous", defaultSelected: false },
    ],
  },
  {
    id: "9",
    title: "Steak & Potato Bowl",
    rating: 4.9,
    addOns: ["Horseradish", "Gravy", "Cheddar Cheese", "Mushrooms"],
    bowls: 2,
    persons: 1,
    price: 15.0,
    imageUrl: "/demo.jpg",
    itemDetails:
      "Juicy steak served with roasted potatoes, sautéed mushrooms, and your choice of horseradish or gravy. This hearty bowl is packed with flavor and is sure to satisfy even the biggest appetites.",

    fetchFillings: async () => [
      { id: "1", name: "Ribeye", defaultSelected: true },
      { id: "2", name: "Sirloin", defaultSelected: false },
      { id: "3", name: "Flank", defaultSelected: false },
      { id: "4", name: "Filet Mignon", defaultSelected: false },
      { id: "5", name: "Porterhouse", defaultSelected: false },
    ],
  },
  {
    id: "10",
    title: "Classic Burger Bowl",
    rating: 4.6,
    addOns: ["Cheddar", "Lettuce", "Tomato", "Bacon"],
    bowls: 2,
    persons: 1,
    price: 8.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A bowl version of a classic burger, with all the essentials: a juicy beef patty, crisp lettuce, fresh tomato, and melted cheddar cheese. Add bacon for extra flavor, served over your choice of greens or fries.",

    fetchFillings: async () => [
      { id: "1", name: "Beef Patty", defaultSelected: true },
      { id: "2", name: "Chicken Patty", defaultSelected: false },
      { id: "3", name: "Veggie Patty", defaultSelected: false },
      { id: "4", name: "Turkey Patty", defaultSelected: false },
      { id: "5", name: "Fish Fillet", defaultSelected: false },
    ],
  },
  {
    id: "10",
    title: "Classic Burger Bowl",
    rating: 4.6,
    addOns: ["Cheddar", "Lettuce", "Tomato", "Bacon"],
    bowls: 2,
    persons: 1,
    price: 8.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A bowl version of a classic burger, with all the essentials: a juicy beef patty, crisp lettuce, fresh tomato, and melted cheddar cheese. Add bacon for extra flavor, served over your choice of greens or fries.",

    fetchFillings: async () => [
      { id: "1", name: "Beef Patty", defaultSelected: true },
      { id: "2", name: "Chicken Patty", defaultSelected: false },
      { id: "3", name: "Veggie Patty", defaultSelected: false },
      { id: "4", name: "Turkey Patty", defaultSelected: false },
      { id: "5", name: "Fish Fillet", defaultSelected: false },
    ],
  },
  {
    id: "10",
    title: "Classic Burger Bowl",
    rating: 4.6,
    addOns: ["Cheddar", "Lettuce", "Tomato", "Bacon"],
    bowls: 2,
    persons: 1,
    price: 8.99,
    imageUrl: "/demo.jpg",
    itemDetails:
      "A bowl version of a classic burger, with all the essentials: a juicy beef patty, crisp lettuce, fresh tomato, and melted cheddar cheese. Add bacon for extra flavor, served over your choice of greens or fries.",

    fetchFillings: async () => [
      { id: "1", name: "Beef Patty", defaultSelected: true },
      { id: "2", name: "Chicken Patty", defaultSelected: false },
      { id: "3", name: "Veggie Patty", defaultSelected: false },
      { id: "4", name: "Turkey Patty", defaultSelected: false },
      { id: "5", name: "Fish Fillet", defaultSelected: false },
    ],
  },
];
export const categories: CategoryTypes = [
  { value: "all", label: "All" },
  { value: "pizza", label: "Pizza" },
  { value: "fast-food", label: "Fast Food" },
  { value: "noodle", label: "Noodle" },
  { value: "dessert", label: "Dessert" },
  { value: "sea-food", label: "Sea Food" },
  { value: "sushi", label: "Sushi" },
  { value: "ramen", label: "Ramen" },
  { value: "pasta", label: "Pasta" },
  { value: "burger", label: "Burger" },
  { value: "salad", label: "Salad" },
  { value: "sandwich", label: "Sandwich" },
  { value: "steak", label: "Steak" },
  { value: "bbq", label: "BBQ" },
  { value: "fried-chicken", label: "Fried Chicken" },
  { value: "tacos", label: "Tacos" },
  { value: "burrito", label: "Burrito" },
  { value: "ice-cream", label: "Ice Cream" },
  { value: "shakes", label: "Shakes" },
  { value: "drinks", label: "Drinks" },
];

export const tableDataset: Table[] = [
  {
    id: 1,
    name: "Table 1",
    chairs: 4,
    status: "available",
  },
  {
    id: 2,
    name: "Table 2",
    chairs: 2,
    status: "occupied",
    customerName: "John Doe",
  },
  {
    id: 3,
    name: "Table 3",
    chairs: 6,
    status: "reserved",
    reservationName: "Jane Smith",
    reservationTime: "2024-10-27T19:00:00.000Z",
  },
  {
    id: 4,
    name: "Table 4",
    chairs: 4,
    status: "available",
  },
  {
    id: 5,
    name: "Table 5",
    chairs: 2,
    status: "occupied",
    customerName: "Alice Johnson",
  },
  {
    id: 6,
    name: "Table 6",
    chairs: 8,
    status: "reserved",
    reservationName: "Bob Williams",
    reservationTime: "2024-10-27T20:30:00.000Z",
  },
  {
    id: 7,
    name: "Table 7",
    chairs: 4,
    status: "available",
  },
  {
    id: 8,
    name: "Table 8",
    chairs: 2,
    status: "occupied",
    customerName: "Eva Garcia",
  },
  {
    id: 9,
    name: "Table 9",
    chairs: 6,
    status: "reserved",
    reservationName: "David Rodriguez",
    reservationTime: "2024-10-28T12:00:00.000Z",
  },
  {
    id: 10,
    name: "Table 10",
    chairs: 4,
    status: "available",
  },
  {
    id: 11,
    name: "Table 11",
    chairs: 6,
    status: "reserved",
    reservationName: "Michael Brown",
    reservationTime: "2024-10-28T18:00:00.000Z",
  },
  {
    id: 12,
    name: "Table 12",
    chairs: 8,
    status: "occupied",
    customerName: "Sophie Turner",
  },
  {
    id: 13,
    name: "Table 13",
    chairs: 4,
    status: "available",
  },
  {
    id: 14,
    name: "Table 14",
    chairs: 2,
    status: "occupied",
    customerName: "Tom Hanks",
  },
  {
    id: 15,
    name: "Table 15",
    chairs: 6,
    status: "reserved",
    reservationName: "Emily White",
    reservationTime: "2024-10-28T15:00:00.000Z",
  },
];
